:set number " 显示行号
:set shiftwidth=4 " 缩进长度
:set softtabstop=4 " tab长度
:set autoindent " 自动缩进
":set list " 显示tab
:set ruler " 显示光标位置
:set showcmd " 显示命令
:colorscheme molokai " 配色
:set hlsearch " 高亮搜索
:set incsearch " 搜索输入时高亮
:set scrolloff=3 " 光标上下行数
